name: nanaz-bot

services:
  nanaz-bot:
    build: .
    image: nanaz-bot
    container_name: nanaz-bot
    env_file:
      - .env
    depends_on:
      - nanazdb
    command: sh -c "npm run syncdb && node dist/index.js"
    networks:
      - nanaz-network

  nanazdb:
    image: postgres:18-alpine
    container_name: nanazdb
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - nanaz-network

  adminer:
    image: adminer
    container_name: nanaz-bot_adminer
    ports:
      - "9090:8080"
    depends_on:
      - nanazdb
    networks:
      - nanaz-network

volumes:
  db_data:

networks:
  nanaz-network:
    driver: bridge
